server:
  port: ${port:8101}

eureka:
  instance:
    # Discover Servery try to look-up hostname for resolving client services.
    hostname: ${CUSTOMER_HOSTNAME:localhost}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    # Following properties "ip-address and prefer-ip-address" for accessing application within container of docker.
    #ip-address: 192.168.0.113
    #prefer-ip-address: true 
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOSTNAME:localhost}:8761/eureka/

management:
  security:
    enabled: false
    
logging:
  level:
    org.chiwooplatform.cloud.sample.rest: DEBUG 
    org.chiwooplatform.cloud.sample: DEBUG
      
