server:
  port: ${port:8101}

spring:
  application:
    name: customer-service
  cloud:
    config:
      uri: http://${CONFIG_SERVICE_DOMAIN:localhost}:8888
      name: customer-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_DOMAIN:localhost}:8761/eureka/

management:
  security:
    enabled: false
    
logging:
  level:
    org.chiwooplatform.cloud.sample.rest: DEBUG 
    org.chiwooplatform.cloud.sample: DEBUG
      
